<?
// NOME DO ERRO NO SITE AO ENTRAR EM LUGAR NÃO AUTORIZADO
$tituloerro="NetworkPK";

// ** START SCRIPTS ** \\

// IP CORRETO DO SERVIDOR LOCAL PARA MOSTRA STATUS ONLINE (SITE)
$iplocal="189.79.242.5:31206";

// DIRETORIO DO BLESSCASTLE.DAT
$diretoriobc="'C:/Server/BlessCastle.dat'";

// PORTA DO SERVER.EXE CORRETA
$portasv="30010";

// NOME E INSTANCIA DA MAQUINA
$instanciasql="PTL\SQLEXPRESS";

// USER DO SQL LOCAL
$usersql="sa";

// PW SQL LOCAL
$pwsql="#$pdl32xq";
?>
